# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-03 20:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_userclassdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classdata',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='classdata',
            name='class_code',
            field=models.CharField(default=datetime.datetime(2018, 4, 3, 20, 11, 51, 628446, tzinfo=utc), max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classdata',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
