# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-03 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20180403_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classdata',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
