# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-03 15:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('time_limit', models.IntegerField(default=0)),
                ('input_data_file', models.FileField(upload_to='stdin/')),
                ('output_data_file', models.FileField(upload_to='stdout/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.ClassData')),
            ],
        ),
    ]
