# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-04-03 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmissionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.FileField(upload_to='submission/')),
                ('time_taken', models.IntegerField(default=0)),
                ('response', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assignment_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.AssignmentData')),
                ('user_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserData')),
            ],
        ),
    ]
