# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-05-14 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignmentsubmissiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentdata',
            name='time_limit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assignmentsubmissiondata',
            name='submitted_code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assignmentsubmissiondata',
            name='time_taken',
            field=models.FloatField(default=0),
        ),
    ]
