# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-05-15 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20180514_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentTestCaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_input', models.TextField()),
                ('case_output', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assignment_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.AssignmentData')),
            ],
        ),
    ]
